name: CI
# this avoids duplicated builds on pull request for the cost
on:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.8"]
        poetry-version: ["1.3"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install --with dev
      - name: Install CORSIKA7
        run: admin/download_corsika.sh
        env:
          CORSIKA_PW: ${{ secrets.CORSIKA_PW }}
      - name: Run tests
        run: poetry run coverage run --include="panama/**" -m pytest
      - name: Produce coverage xml
        run: poetry run coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
